import { assertEquals } from "https://deno.land/std/testing/asserts.ts";
import { Input } from "../../utils/deno/input.ts";

import { Cell, Universe, solvePart1, expand } from "./solutions.ts";

Deno.test("part 1 - given test case", () => {
  const input = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`;

  assertEquals(solvePart1(new Input(input)), 374);
});

Deno.test("part 1 - expand", () => {
  const input = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`;

  const universe: Universe = new Input(input).lines.map(
    (x) => x.split("") as Cell[]
  );

  const expected = `....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......`;

  assertEquals(
    expand(universe)
      .map((x) => x.join(""))
      .join("\n"),
    expected
  );
});
